# go-sql 数据库配置 (如果提供了此部分，go-sql 模块将被自动初始化)
# 使用 golang 标准库 database/sql 初始化数据库连接池，支持 mysql, postgres, sqlite3 等数据库
# 确保配置文件与 ORM 框架解耦，替换底层 ORM 框架时，无需修改配置文件。
go-sql:
  # ------------------- MySQL (默认启用) -------------------
  # DSN (Data Source Name) 格式: username:password@tcp(host:port)/dbname?charset=utf8mb4&parseTime=True&loc=Local
  driver: "mysql"
  dsn: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"

  # ------------------- PostgreSQL -------------------
  # DSN (Data Source Name) 格式: postgres://user:password@host:port/dbname?sslmode=disable
  # driver: "postgres"
  # dsn: "postgres://user:password@localhost:5432/mydatabase?sslmode=disable"

  # ------------------- SQLite3 -------------------
  # DSN (Data Source Name) 格式: /path/to/database.db
  # driver: "sqlite3"
  # dsn: "data/go-project.db"

  # ------------------- Oracle -------------------
  # DSN (Data Source Name) 格式: user/password@host:port/dbname
  # driver: "oracle"
  # dsn: "user/password@host:port/dbname"

  # ------------------- SQL Server -------------------
  # DSN (Data Source Name) 格式: server=host;user id=user;password=password;database=dbname
  # driver: "sqlserver"
  # dsn: "server=host;user id=user;password=password;database=dbname"

  # --- 连接池配置 (通用) ---
  max_open_conns: 20 # 最大打开连接数
  max_idle_conns: 10 # 最大空闲连接数
  conn_max_lifetime: 3600 # 连接最大生命周期(秒)
  conn_max_idle_time: 3600 # 连接最大空闲时间(秒)