# go-sql 数据库配置 (如果提供了此部分，mysql 模块将被自动初始化)
# 使用 golang 标准库 database/sql 初始化数据库连接池，支持 mysql, postgres, sqlite3 等数据库
# 确保配置文件与 ORM 框架解耦，替换底层 ORM 框架时，无需修改配置文件。
go-sql:
  driver: "mysql"
  dsn: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 3600