# GORM 框架配置
gorm:
  # 数据库驱动，与 go-sql 中的 driver 保持一致
  # 支持: mysql, postgres, sqlite3, sqlserver
  driver: "mysql"

  # DSN (Data Source Name)，用于连接数据库
  # GORM 会复用 go-sql 的连接池，所以这里只需要提供连接信息
  # MySQL:         "user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"
  # PostgreSQL:    "host=localhost user=gorm password=gorm dbname=gorm port=9920 sslmode=disable"
  # SQLite:        "gorm.db"
  dsn: "root:123456@tcp(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"

  # GORM 相关配置
  config:
    # 全局表前缀
    table_prefix: "t_"
    # 禁用外键约束 (生产环境建议关闭)
    disable_foreign_key_constraint_when_migrating: true
    # GORM 日志级别: silent, info, warn, error
    log_level: "info"
    # 慢查询阈值 (毫秒)
    slow_threshold_ms: 200 