# app-dev.yaml 配置

# 自动配置的模块 ================================================

# slog 日志配置 (如果提供了此部分，logger 模块将被自动初始化)
log:
  # 控制台输出配置
  console:
    enable_console: true
    level: "debug"
    add_source: true
    console_format: "text"
  # 文件输出配置
  file:
    enable_file: true
    level: "info"
    path: "logs"
    filename: "default.log"
    add_source: true
    file_format: "json"
    file_max_size: 100
    file_max_backups: 3
    file_max_age: 7
    file_compress: false

# Redis 配置 (如果提供了此部分，redis 模块将被自动初始化)
redis:
  addr: "10.123.1.47:6379" # optional: default 127.0.0.1:6379
  pool_size: 1 # optional: default 10

# gosql 数据库配置 (如果提供了此部分，gosql 模块将被自动初始化)
gosql:
  driver: "mysql"
  dsn: "root:123456@tcp(10.123.1.47:5807)/test_cloud_img?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conns: 20
  max_idle_conns: 10
  conn_max_lifetime: 3600

# mysql:
#   host: "127.0.0.1"
#   port: 3306
#   username: "root"
#   password: "your_password"
#   database: "your_db"
#   max_open_conns: 20
#   max_idle_conns: 10
#   conn_max_lifetime: 3600 # 秒

# gin 配置 (如果提供了此部分，gin 模块将被自动初始化)
gin:
  mode: debug # 可选 debug, release, test, 默认 debug
  port: 8888 # 可选 8080, 默认 8080
  read_timeout: 10 # 可选 10, 默认 10
  write_timeout: 10 # 可选 10, 默认 10
  max_header_bytes: 1024 # 可选 1024, 默认 1024

# Nats 配置 (如果提供了此部分，nats 模块将被自动初始化)
# nats:
#   url: "nats://127.0.0.1:4222"
#   # ... 其他 nats 相关配置

# # Kafka 配置 (如果提供了此部分，kafka 模块将被自动初始化)
# kafka:
#   brokers:
#     - "127.0.0.1:9092"
#   # ... 其他 kafka 相关配置

# 手动配置的模块 ================================================

other:
  name: "zhangsan"
  age: 18
  address: "beijing"
  phone: "1234567890"
  job: "developer"